//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonteRemoteTest.MonteCarloService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MonteCarloService.IMonteCarloService")]
    public interface IMonteCarloService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonteCarloService/GetCallPrice", ReplyAction="http://tempuri.org/IMonteCarloService/GetCallPriceResponse")]
        MonteRemoteTest.MonteCarloService.GetCallPriceResponse GetCallPrice(MonteRemoteTest.MonteCarloService.GetCallPriceRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonteCarloService/GetCallPrice", ReplyAction="http://tempuri.org/IMonteCarloService/GetCallPriceResponse")]
        System.Threading.Tasks.Task<MonteRemoteTest.MonteCarloService.GetCallPriceResponse> GetCallPriceAsync(MonteRemoteTest.MonteCarloService.GetCallPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonteCarloService/GetPutPrice", ReplyAction="http://tempuri.org/IMonteCarloService/GetPutPriceResponse")]
        MonteRemoteTest.MonteCarloService.GetPutPriceResponse GetPutPrice(MonteRemoteTest.MonteCarloService.GetPutPriceRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonteCarloService/GetPutPrice", ReplyAction="http://tempuri.org/IMonteCarloService/GetPutPriceResponse")]
        System.Threading.Tasks.Task<MonteRemoteTest.MonteCarloService.GetPutPriceResponse> GetPutPriceAsync(MonteRemoteTest.MonteCarloService.GetPutPriceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCallPrice", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCallPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public double num_sums;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public double S;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public double L;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public double r;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public double v;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public double T;
        
        public GetCallPriceRequest() {
        }
        
        public GetCallPriceRequest(double num_sums, double S, double L, double r, double v, double T) {
            this.num_sums = num_sums;
            this.S = S;
            this.L = L;
            this.r = r;
            this.v = v;
            this.T = T;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCallPriceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCallPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public double GetCallPriceResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public double num_sums;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public double S;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public double L;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public double r;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public double v;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public double T;
        
        public GetCallPriceResponse() {
        }
        
        public GetCallPriceResponse(double GetCallPriceResult, double num_sums, double S, double L, double r, double v, double T) {
            this.GetCallPriceResult = GetCallPriceResult;
            this.num_sums = num_sums;
            this.S = S;
            this.L = L;
            this.r = r;
            this.v = v;
            this.T = T;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPutPrice", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPutPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public double num_sums;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public double S;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public double L;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public double r;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public double v;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public double T;
        
        public GetPutPriceRequest() {
        }
        
        public GetPutPriceRequest(double num_sums, double S, double L, double r, double v, double T) {
            this.num_sums = num_sums;
            this.S = S;
            this.L = L;
            this.r = r;
            this.v = v;
            this.T = T;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPutPriceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPutPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public double GetPutPriceResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public double num_sums;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public double S;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public double L;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public double r;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public double v;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public double T;
        
        public GetPutPriceResponse() {
        }
        
        public GetPutPriceResponse(double GetPutPriceResult, double num_sums, double S, double L, double r, double v, double T) {
            this.GetPutPriceResult = GetPutPriceResult;
            this.num_sums = num_sums;
            this.S = S;
            this.L = L;
            this.r = r;
            this.v = v;
            this.T = T;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMonteCarloServiceChannel : MonteRemoteTest.MonteCarloService.IMonteCarloService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonteCarloServiceClient : System.ServiceModel.ClientBase<MonteRemoteTest.MonteCarloService.IMonteCarloService>, MonteRemoteTest.MonteCarloService.IMonteCarloService {
        
        public MonteCarloServiceClient() {
        }
        
        public MonteCarloServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonteCarloServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonteCarloServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonteCarloServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MonteRemoteTest.MonteCarloService.GetCallPriceResponse MonteRemoteTest.MonteCarloService.IMonteCarloService.GetCallPrice(MonteRemoteTest.MonteCarloService.GetCallPriceRequest request) {
            return base.Channel.GetCallPrice(request);
        }
        
        public double GetCallPrice(ref double num_sums, ref double S, ref double L, ref double r, ref double v, ref double T) {
            MonteRemoteTest.MonteCarloService.GetCallPriceRequest inValue = new MonteRemoteTest.MonteCarloService.GetCallPriceRequest();
            inValue.num_sums = num_sums;
            inValue.S = S;
            inValue.L = L;
            inValue.r = r;
            inValue.v = v;
            inValue.T = T;
            MonteRemoteTest.MonteCarloService.GetCallPriceResponse retVal = ((MonteRemoteTest.MonteCarloService.IMonteCarloService)(this)).GetCallPrice(inValue);
            num_sums = retVal.num_sums;
            S = retVal.S;
            L = retVal.L;
            r = retVal.r;
            v = retVal.v;
            T = retVal.T;
            return retVal.GetCallPriceResult;
        }
        
        public System.Threading.Tasks.Task<MonteRemoteTest.MonteCarloService.GetCallPriceResponse> GetCallPriceAsync(MonteRemoteTest.MonteCarloService.GetCallPriceRequest request) {
            return base.Channel.GetCallPriceAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MonteRemoteTest.MonteCarloService.GetPutPriceResponse MonteRemoteTest.MonteCarloService.IMonteCarloService.GetPutPrice(MonteRemoteTest.MonteCarloService.GetPutPriceRequest request) {
            return base.Channel.GetPutPrice(request);
        }
        
        public double GetPutPrice(ref double num_sums, ref double S, ref double L, ref double r, ref double v, ref double T) {
            MonteRemoteTest.MonteCarloService.GetPutPriceRequest inValue = new MonteRemoteTest.MonteCarloService.GetPutPriceRequest();
            inValue.num_sums = num_sums;
            inValue.S = S;
            inValue.L = L;
            inValue.r = r;
            inValue.v = v;
            inValue.T = T;
            MonteRemoteTest.MonteCarloService.GetPutPriceResponse retVal = ((MonteRemoteTest.MonteCarloService.IMonteCarloService)(this)).GetPutPrice(inValue);
            num_sums = retVal.num_sums;
            S = retVal.S;
            L = retVal.L;
            r = retVal.r;
            v = retVal.v;
            T = retVal.T;
            return retVal.GetPutPriceResult;
        }
        
        public System.Threading.Tasks.Task<MonteRemoteTest.MonteCarloService.GetPutPriceResponse> GetPutPriceAsync(MonteRemoteTest.MonteCarloService.GetPutPriceRequest request) {
            return base.Channel.GetPutPriceAsync(request);
        }
    }
}
